package launch

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/docker/sbx-kits-contrib/spec"
)

func load(t *testing.T, sandbox string) *spec.Manifest {
	t.Helper()
	a, err := spec.LoadArtifactFromBytes([]byte("schemaVersion: \"2\"\nkind: sandbox\nname: k\nsandbox:\n  image: img\n" + sandbox))
	require.NoError(t, err)
	return &a.Manifest
}

func TestFromManifest(t *testing.T) {
	tests := []struct {
		name string
		m    *spec.Manifest
		want Recipe
	}{
		{
			name: "v2 list command",
			m:    load(t, "  entrypoint: [agent, sub]\n  command: [--model, sonnet]\n"),
			want: Recipe{Version: 1, Kind: KindAgent, Binary: "agent", FixedArgs: []string{"sub"}, DefaultArgs: []string{"--model", "sonnet"}},
		},
		{
			name: "v2 interactive wins",
			m:    load(t, "  entrypoint: [agent]\n  command:\n    default: [--headless]\n    interactive: [--tui]\n"),
			want: Recipe{Version: 1, Kind: KindAgent, Binary: "agent", DefaultArgs: []string{"--tui"}},
		},
		{
			name: "v2 absent interactive uses default",
			m:    load(t, "  entrypoint: [agent]\n  command:\n    default: [--headless]\n"),
			want: Recipe{Version: 1, Kind: KindAgent, Binary: "agent", DefaultArgs: []string{"--headless"}},
		},
		{
			name: "v2 empty interactive means no tail",
			m:    load(t, "  entrypoint: [agent, sub]\n  command:\n    default: [--headless]\n    interactive: []\n"),
			want: Recipe{Version: 1, Kind: KindAgent, Binary: "agent", FixedArgs: []string{"sub"}},
		},
		{
			name: "v2 shell kit",
			m:    load(t, "  command: [-l]\n"),
			want: Recipe{Version: 1, Kind: KindShell},
		},
		{
			name: "flat only",
			m:    &spec.Manifest{Binary: "agent", RunOptions: []string{"--a", "b"}},
			want: Recipe{Version: 1, Kind: KindAgent, Binary: "agent", DefaultArgs: []string{"--a", "b"}, Legacy: true},
		},
		{
			name: "flat interactive preferred",
			m:    &spec.Manifest{Binary: "agent", RunOptions: []string{"--a"}, InteractiveOptions: []string{"--i"}},
			want: Recipe{Version: 1, Kind: KindAgent, Binary: "agent", DefaultArgs: []string{"--i"}, Legacy: true},
		},
		{
			// A child that extends claude with command [--model, sonnet]
			// after a field-by-field merge: the flat fields hold the
			// effective command, Launch is the parent's. The recipe must
			// not bring the parent's permission flag back.
			name: "inherited stale launch",
			m: &spec.Manifest{
				Binary:             "claude",
				RunOptions:         []string{"--model", "sonnet"},
				InteractiveOptions: []string{"--model", "sonnet"},
				Launch:             &spec.Launch{Entrypoint: []string{"claude", "--dangerously-skip-permissions"}},
			},
			want: Recipe{Version: 1, Kind: KindAgent, Binary: "claude", DefaultArgs: []string{"--model", "sonnet"}, Legacy: true},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := FromManifest(tt.m)
			require.Equal(t, tt.want, got)
			require.NoError(t, got.Validate())
		})
	}
}

func TestValidate(t *testing.T) {
	bad := []Recipe{
		{Version: 2, Kind: KindAgent, Binary: "a"},
		{Version: 1, Kind: "other", Binary: "a"},
		{Version: 1, Kind: KindAgent},
		{Version: 1, Kind: KindAgent, Binary: "-a"},
		{Version: 1, Kind: KindAgent, Binary: "a", FixedArgs: []string{"x"}, Legacy: true},
		{Version: 1, Kind: KindAgent, Binary: "a", DefaultArgs: []string{"x\x00y"}},
		{Version: 1, Kind: KindShell, Binary: "bash"},
		{Version: 1, Kind: KindShell, DefaultArgs: []string{"-l"}},
	}
	for _, r := range bad {
		require.Error(t, r.Validate(), "%+v", r)
		_, err := Render(r)
		require.Error(t, err)
	}
	_, err := Render(Recipe{Version: 1, Kind: KindShell})
	require.Error(t, err, "a shell recipe has no launcher")
}

func TestInvocation(t *testing.T) {
	require.Equal(t, []string{"/bin/sh", "/usr/local/lib/sandbox/start-agent"}, Invocation())
	require.Equal(t, []string{"/bin/sh", LauncherPath, "", "--", "a b"}, Invocation("", "--", "a b"))
}

func TestRenderedHeader(t *testing.T) {
	b, err := Render(Recipe{Version: 1, Kind: KindAgent, Binary: "agent"})
	require.NoError(t, err)
	require.True(t, bytes.HasPrefix(b, []byte("#!/bin/sh\n# Generated by Docker Sandboxes")))
	require.NotContains(t, string(b), "bash_env", "no helper variables leak into the agent")
}

// shell runs the launcher script under one interpreter.
type shell struct {
	name string
	argv []string // interpreter argv; the script path and user args follow
	// bashOnPath says whether bash is on the PATH the script sees.
	bashOnPath bool
	// wantSourced is how many times BASH_ENV must be read.
	wantSourced int
}

func shells(t *testing.T) []shell {
	var out []shell
	bash, _ := exec.LookPath("bash")
	withBash := bash != ""
	sourced := 0
	if withBash {
		sourced = 1
	}
	// /bin/sh is dash on Debian/Ubuntu, bash in POSIX mode on macOS and
	// busybox on Alpine; all must read BASH_ENV once when bash exists.
	out = append(out, shell{name: "sh", argv: []string{"/bin/sh"}, bashOnPath: withBash, wantSourced: sourced})
	out = append(out, shell{name: "sh-no-bash", argv: []string{"/bin/sh"}})
	if withBash {
		// Older selectors run "bash <launcher>"; bash reads BASH_ENV at
		// startup and the script must not read it again.
		out = append(out, shell{name: "bash", argv: []string{bash}, bashOnPath: true, wantSourced: 1})
		out = append(out, shell{name: "bash-no-bash-on-path", argv: []string{bash}, wantSourced: 1})
	}
	for _, alt := range [][]string{{"dash"}, {"busybox", "sh"}} {
		p, err := exec.LookPath(alt[0])
		if err != nil {
			continue
		}
		argv := append([]string{p}, alt[1:]...)
		out = append(out, shell{name: strings.Join(alt, "-"), argv: argv, bashOnPath: withBash, wantSourced: sourced})
		out = append(out, shell{name: strings.Join(alt, "-") + "-no-bash", argv: argv})
	}
	t.Logf("shells: %d, bash at %q", len(out), bash)
	return out
}

func TestRenderedLauncherRuns(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("needs a POSIX shell")
	}
	structured := Recipe{Version: 1, Kind: KindAgent, Binary: "agent",
		FixedArgs: []string{"sub", "--fixed"}, DefaultArgs: []string{"--model", "son net"}}
	awkward := []string{"it's", `$HOME`, "a b", "line1\nline2", "", "`id`", `\`, "*", `"q"`, "$(echo hi)", "-"}
	cases := []struct {
		name   string
		recipe Recipe
		args   []string
		want   []string
	}{
		{"no args", structured, nil, []string{"sub", "--fixed", "--model", "son net"}},
		{"leading flag", structured, []string{"--x", "y"}, []string{"sub", "--fixed", "--model", "son net", "--x", "y"}},
		{"positional", structured, []string{"run", "--x"}, []string{"sub", "--fixed", "run", "--x"}},
		{"empty first arg", structured, []string{"", "z"}, []string{"sub", "--fixed", "--model", "son net", "", "z"}},
		{"double dash", structured, []string{"--", "run"}, []string{"sub", "--fixed", "--model", "son net", "--", "run"}},
		{"positional then double dash", structured, []string{"run", "--", "-x"}, []string{"sub", "--fixed", "run", "--", "-x"}},
		{"legacy sub-command", Recipe{Version: 1, Kind: KindAgent, Binary: "agent", DefaultArgs: []string{"--model", "sonnet"}, Legacy: true},
			[]string{"agents"}, []string{"agents"}},
		{"no default tail", Recipe{Version: 1, Kind: KindAgent, Binary: "agent", FixedArgs: []string{"x"}}, []string{"--y"}, []string{"x", "--y"}},
		{"quoting in recipe", Recipe{Version: 1, Kind: KindAgent, Binary: "agent", FixedArgs: awkward, DefaultArgs: awkward},
			nil, append(append([]string{}, awkward...), awkward...)},
		{"quoting in user args", Recipe{Version: 1, Kind: KindAgent, Binary: "agent"}, awkward, awkward},
	}

	for _, sh := range shells(t) {
		t.Run(sh.name, func(t *testing.T) {
			for _, tc := range cases {
				t.Run(tc.name, func(t *testing.T) {
					got, sourced := runLauncher(t, sh, tc.recipe, tc.args, true)
					require.Equal(t, tc.want, got)
					require.Equal(t, sh.wantSourced, sourced, "BASH_ENV reads")
				})
			}
			t.Run("no BASH_ENV", func(t *testing.T) {
				got, sourced := runLauncher(t, sh, structured, []string{"run"}, false)
				require.Equal(t, []string{"sub", "--fixed", "run"}, got)
				require.Zero(t, sourced)
			})
		})
	}
}

// runLauncher renders r, runs it under sh with args and returns the argv the
// fake agent received (without argv[0]) and how often BASH_ENV was read.
func runLauncher(t *testing.T, sh shell, r Recipe, args []string, withBashEnv bool) ([]string, int) {
	t.Helper()
	dir := t.TempDir()
	script, err := Render(r)
	require.NoError(t, err)
	launcher := filepath.Join(dir, "start-agent")
	require.NoError(t, os.WriteFile(launcher, script, 0o755))

	// The fake agent lives in its own directory. When BASH_ENV is read it
	// adds that directory to PATH, which also proves the PATH lookup
	// happens after the persistent environment is loaded.
	agentDir := filepath.Join(dir, "agentbin")
	require.NoError(t, os.Mkdir(agentDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(agentDir, "agent"),
		[]byte("#!/bin/sh\nfor a do printf '%s\\0' \"$a\"; done > \"$ARGV_OUT\"\n"), 0o755))

	// A PATH directory that has bash only when the case wants it.
	toolDir := filepath.Join(dir, "tools")
	require.NoError(t, os.Mkdir(toolDir, 0o755))
	if sh.bashOnPath {
		bash, err := exec.LookPath("bash")
		require.NoError(t, err)
		require.NoError(t, os.Symlink(bash, filepath.Join(toolDir, "bash")))
	}

	argvOut := filepath.Join(dir, "argv")
	countOut := filepath.Join(dir, "count")
	bashEnv := filepath.Join(dir, "persistent.sh")
	require.NoError(t, os.WriteFile(bashEnv,
		[]byte("echo x >> \"$COUNT_OUT\"\nPATH=\"$AGENT_DIR:$PATH\"\n"), 0o644))

	path := toolDir
	if !withBashEnv || !sh.bashOnPath && !strings.HasSuffix(sh.argv[0], "bash") {
		// Nothing will read BASH_ENV, so the agent must already be on PATH.
		path = agentDir + ":" + toolDir
	}
	env := []string{"PATH=" + path, "ARGV_OUT=" + argvOut, "COUNT_OUT=" + countOut, "AGENT_DIR=" + agentDir}
	if withBashEnv {
		env = append(env, "BASH_ENV="+bashEnv)
	}
	cmd := exec.Command(sh.argv[0], append(append(append([]string{}, sh.argv[1:]...), launcher), args...)...)
	cmd.Env = env
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "launcher output: %s\nscript:\n%s", out, script)

	raw, err := os.ReadFile(argvOut)
	require.NoError(t, err)
	var got []string
	if len(raw) > 0 {
		got = strings.Split(strings.TrimSuffix(string(raw), "\x00"), "\x00")
	}
	count := 0
	if c, err := os.ReadFile(countOut); err == nil {
		count = strings.Count(string(c), "x\n")
	}
	return got, count
}
